default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  encoding: unicode
  timeout: 5000

development:
  <<: *default
  database: chat_app_dev

test:
  <<: *default
  database: chat_app_test

production:
  <<: *default
  database: chat_app
